name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: [ "5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1" ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          PHP_VERSION: ${{ matrix.php_version }}
        run: |
          set -eux
          image_tag=${{ matrix.php_version }}  | sed 's/\.//'
          docker build -f ./Dockerfile-${{ image_tag }}-fpm -t ${{ secrets.DOCKER_ORGANIZATION }}/base-ws:php-${{ matrix.php_version }} .
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push ${DOCKER_ORGANIZATION}/base-ws:${{ image_tag }}

