name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: [ ["56", "5.6"], ["70", "7.0"], ["71", "7.1"], ["72", "7.2"], ["73", "7.3"], ["74", "7.4"], ["80", "8.0"] ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          WITHOUT_DOT: ${{ matrix.php_version[0] }}
          WITH_DOT: ${{ matrix.php_version[1] }}
        run: |
          set -eux
          docker build -f ./Dockerfile-${{WITHOUT_DOT}}-fpm -t ${{ secrets.DOCKER_ORGANIZATION }}/base-ws:${{WITH_DOT}}-fpm .
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push ${DOCKER_ORGANIZATION}/base-ws:${{WITH_DOT}}-fpm

