name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        data: [ ["php56", "php5.6"], ["php70", "php7.0"], ["php71", "php7.1"], ["php72", "php7.2"], ["php73", "php7.3"], ["php74", "php7.4"], ["php80", "php8.0"], ["general", "general"] ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          FILE_IDENTIFIER: ${{ matrix.data[0] }}
          TAG_NAME: ${{ matrix.data[1] }}
        run: |
          set -eux
          docker build -f ./Dockerfile-$FILE_IDENTIFIER -t ${{ secrets.DOCKER_ORGANIZATION }}/base-ws:$TAG_NAME .
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push ${DOCKER_ORGANIZATION}/base-ws:$TAG_NAME

